# Based on https://github.com/actions/starter-workflows/pull/47#issuecomment-537846624
name: C++ CI

on: [push]

jobs:
  build_and_test_cpp_only:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build GameOfLife C++
      run: cmake --build build
    - name: unit-tests for GameOfLife C++
      run: build/test/GameOfLifeTests

jobs:
  build_godot_release_job_WIP:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Checkout submodules (eg. godot)
      uses: git submodules update --init --recursive
      